apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: react-deployment
  name: react-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-deployment
  template:
    metadata:
      labels:
        app: react-deployment
    spec:
      containers:
      - image: vuthehuyt61/react-template:main
        imagePullPolicy: Always
        name: react-deployment
        ports:
        - containerPort: 80
