apiVersion: v1
kind: Service
metadata:
  labels:
    app: react-service
  name: react-service
spec:
  ports:
  - port: 80
    name: react-service
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
  selector:
    app: react-deployment
